name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -L -v https://pdfdarkmodeconverter.streamlit.app/
